<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak">
        <h1>تنظیمات اولیه پروژه</h1>   
    </font>  
</div>

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak">
        <h2>بارگذاری کتابخانه های مورد نیاز</h2>   
    </font>  
</div>

In [2]:
import platform
import numpy as np
import pandas as pd
from datetime import datetime
import geopandas as gpd
from IPython.display import display

pd.options.display.max_columns = None
pd.options.display.max_rows = 10
pd.options.display.float_format = "{:,.2f}".format

%config Completer.use_jedi = False

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak">
        <h2>تعیین محل فولدر پروژه</h2>
    </font>  
</div>

In [3]:
PROJECT_PATH = r"C:\thesis\Shirazi_Code\Landscape_Evapotranspiration"

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak">
        <h1>بارگذاری دیتابیس</h1>
    </font>  
</div>

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak" style="font-size:20px">
       در این بخش از خروجی فایل main.ipynb استفاده شده است.
    </font>
</div>

In [6]:
data = pd.read_excel(
    PROJECT_PATH + r"/assets/report/dataset_20260813.xlsx",
    engine = "openpyxl",
    dtype={
        "شناسه": str,
        "منطقه": str,
        "ناحیه": str,
        "پیمان": str,
        "آدرس": str,
        "نوع لکه": str,
        "نوع قلم": str,
        "زیرمجموعه هر قلم": str
    }
)

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak" style="font-size:20px">
         پیش نمایشی از داده ها:
    </font>
</div>

In [7]:
data

,شناسه,منطقه,ناحیه,پیمان,آدرس,نوع لکه,نوع قلم,زیرمجموعه هر قلم,مقدار آیتم,مساحت آدرس,مساحت پیمان,نوع آیتم,نام پیمان,نام لکه,نام نوع لکه,نام نوع قلم,نام زیرمجموعه هر قلم,مقدار آیتم خام
0,01.01.01.001.04-56.07,01,01,01,001,04,56,07,"1,704.00","2,718.00","122,306.00",حجمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,حفظ و نگهداری پرچین,متر مربع,"1,704.00"
1,01.01.01.001.04-51.07,01,01,01,001,04,51,07,784.00,"2,718.00","122,306.00",حجمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,حفظ و نگهداری چمن,متر مربع,784.00
2,01.01.01.001.04-52.07,01,01,01,001,04,52,07,210.00,"2,718.00","122,306.00",حجمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,حفظ و نگهداری گل دایمی,متر مربع,210.00
3,01.01.01.001.04-54.07,01,01,01,001,04,54,07,20.00,"2,718.00","122,306.00",حجمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,حفظ و نگهداری گل فصلی,متر مربع,20.00
4,01.01.01.001.04-07.08,01,01,01,001,04,07,08,365.00,"2,718.00","122,306.00",ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,درخت و درختچه,اصله,365.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28936,13.02.01.039.08-01.07,13,02,01,039,08,01,07,690.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,چمن,متر مربع,690.00
28937,13.02.01.039.08-02.05,13,02,01,039,08,02,05,788.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,گل دایم باغچه های معمولی,سایر گل های دایمی,788.00
28938,13.02.01.039.08-02.03,13,02,01,039,08,02,03,788.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,گل دایم باغچه های معمولی,آبیاری شلنگی,788.00
28939,13.02.01.039.08-02.07,13,02,01,039,08,02,07,788.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,گل دایم باغچه های معمولی,متر مربع,788.00
28940,13.02.01.039.08-02.06,13,02,01,039,08,02,06,80.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,گل دایم باغچه های معمولی,گل رز,80.00

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar" style="font-size:20px">
         ابعاد دیتابیس:
    </font>
</div>

In [8]:
data.shape

(28941, 18)

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar" style="font-size:20px">
        مشخصات کلی دیتابیس:
    </font>
</div>

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28941 entries, 0 to 28940
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   شناسه                 28941 non-null  object
 1   منطقه                 28941 non-null  object
 2   ناحیه                 28941 non-null  object
 3   پیمان                 28941 non-null  object
 4   آدرس                  28941 non-null  object
 5   نوع لکه               28941 non-null  object
 6   نوع قلم               28941 non-null  object
 7   زیرمجموعه هر قلم      28941 non-null  object
 8   مقدار آیتم            28934 non-null  float64
 9   مساحت آدرس            28897 non-null  float64
 10  مساحت پیمان           28941 non-null  float64
 11  نوع آیتم              28941 non-null  object
 12  نام پیمان             28941 non-null  object
 13  نام لکه               28941 non-null  object
 14  نام نوع لکه           28941 non-null  object
 15  نام نوع قلم           28941 non-null  object
 16  نام زیرمجموعه هر قلم  28941 non-null  object
 17  مقدار آیتم خام        28941 non-null  float64
dtypes: float64(4), object(14)
memory usage: 4.0+ MB

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak">
        <h1>محاسبه تبخیرتعرق فضای سبز</h1>
    </font>  
</div>

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak">
        <h2>آماده سازی داده ها</h2>
    </font>  
</div>

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak">
        <right><b>توضیحات:</b></right>    
    </font>    
    <font face="B Koodak">
        <right align="justify">
            از ستون «نام نوع قلم» آیتم های:
            <ul>
                <li>درخت و درختچه</li>
                <li>درختان جنگلی</li>
                 <li>پرچین</li>
                <li>چمن</li>
                <li>گل دائم باغچه های معمولی</li>
                <li>گل دائم فلاورباکسهای سطوح شیب دار</li>
                <li>گل فصل باغچه های معمولی</li>
                <li>گل فصل فلاورباکس های سطوح شیب دار</li>
            </ul>
            و از ستون «نام زیرمجموعه هر قلم» آیتم های:
            <ul>
                <li>آبیاری ثقلی</li>
                <li>آبیاری تانکری</li>
                <li>آبیاری شلنگی</li>
                <li>آبیاری تحت فشار</li>
                <li>اصله</li>
                <li>اصله مستقل</li>
            </ul>
            انتخاب شدند.
        </right>    
    </font>    
</div>

In [10]:
import pandas as pd

# جمع‌آوری و کپی کردن خروجی‌ها به صورت متنی در کلیپ‌برد
output_lines = []

output_lines.append("=== لیست انواع قلم موجود در دیتاست ===")
if "نوع قلم" in data.columns and "نام نوع قلم" in data.columns:
    item_summary = data[["نوع قلم", "نام نوع قلم"]].drop_duplicates().sort_values("نوع قلم")
    output_lines.append(item_summary.to_string(index=False))
    display(item_summary)
else:
    unique_items = str(data["نام نوع قلم"].unique())
    output_lines.append(unique_items)
    print(unique_items)

output_lines.append("\n=== لیست زیرمجموعه‌های هر قلم موجود در دیتاست ===")
if "زیرمجموعه هر قلم" in data.columns and "نام زیرمجموعه هر قلم" in data.columns:
    subitem_summary = data[["زیرمجموعه هر قلم", "نام زیرمجموعه هر قلم"]].drop_duplicates().sort_values("زیرمجموعه هر قلم")
    output_lines.append(subitem_summary.to_string(index=False))
    display(subitem_summary)
else:
    unique_subitems = str(data["نام زیرمجموعه هر قلم"].unique())
    output_lines.append(unique_subitems)
    print(unique_subitems)

# انتقال کل خروجی به کلیپ‌برد سیستم
final_text = "\n".join(output_lines)
pd.DataFrame([final_text]).to_clipboard(index=False, header=False)

      نوع قلم                        نام نوع قلم
8          01                                چمن
10         02           گل دایم باغچه های معمولی
4789       03  گل دایم فلاورباکسهای سطوح شیب دار
14         04            گل فصل باغچه های معمولی
11755      05  گل فصل فلاورباکس های سطوح شیب دار
...       ...                                ...
16         57        حفظ و نگهداری درخت و درختچه
75         91                              معابر
1057       92                  محوطه بازی كودكان
140        93                        فضاهای مسقف
36         94                        آبنما نظافت

[18 rows x 2 columns]

     زیرمجموعه هر قلم نام زیرمجموعه هر قلم
5229               01          آبیاری ثقلی
7                  02        آبیاری تانکری
6                  03         آبیاری شلنگی
23                 04      آبیاری تحت فشار
11                 05    سایر گل های دایمی
10                 06                گل رز
0                  07             متر مربع
4                  08                 اصله
35                 09           اصله مستقل

In [11]:
# نوع قلم:
#     'چمن': '01'
#     'گل دائم باغچه های معمولی': '02'
#     'گل دائم فلاورباکسهای سطوح شیب دار': '03'
#     'گل فصل باغچه های معمولی': '04',
#     'گل فصل فلاورباکس های سطوح شیب دار': '05'
#     'پرچین': '06'
#     'درخت و درختچه': '07'
#     'درختان جنگلی': '08'

# زیرمجموعه هر قلم:
#     'آبیاری ثقلی': '01'
#     'آبیاری تانکری': '02'
#     'آبیاری شلنگی': '03'
#     'آبیاری تحت فشار': '04'
#     'اصله' : '08'چرا
#     'اصله مستقل' : '09'

Items = ["01", "02", "03", "04", "05", "06", "07", "08"]
Subitems = ["01", "02", "03", "04", "08", "09"]

dataset = data.query('`نوع قلم` == @Items')\
.query('`زیرمجموعه هر قلم` == @Subitems')\
.reset_index(drop=True)

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar" style="font-size:20px">
         پیش نمایشی از داده های فیلتر شده:
    </font>
</div>

In [12]:
dataset

,شناسه,منطقه,ناحیه,پیمان,آدرس,نوع لکه,نوع قلم,زیرمجموعه هر قلم,مقدار آیتم,مساحت آدرس,مساحت پیمان,نوع آیتم,نام پیمان,نام لکه,نام نوع لکه,نام نوع قلم,نام زیرمجموعه هر قلم,مقدار آیتم خام
0,01.01.01.001.04-07.08,01,01,01,001,04,07,08,365.00,"2,718.00","122,306.00",ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,درخت و درختچه,اصله,365.00
1,01.01.01.001.04-06.03,01,01,01,001,04,06,03,299.00,"2,718.00","122,306.00",ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,پرچین,آبیاری شلنگی,299.00
2,01.01.01.001.04-06.02,01,01,01,001,04,06,02,"1,405.00","2,718.00","122,306.00",ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,پرچین,آبیاری تانکری,"1,405.00"
3,01.01.01.001.04-01.03,01,01,01,001,04,01,03,784.00,"2,718.00","122,306.00",ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,چمن,آبیاری شلنگی,784.00
4,01.01.01.001.04-02.03,01,01,01,001,04,02,03,210.00,"2,718.00","122,306.00",ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,گل دایم باغچه های معمولی,آبیاری شلنگی,210.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11115,13.02.01.038.08-04.03,13,02,01,038,08,04,03,14.00,"1,174.70","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک سارا,پارک های زیر 6 هکتار,گل فصل باغچه های معمولی,آبیاری شلنگی,14.00
11116,13.02.01.039.08-07.08,13,02,01,039,08,07,08,49.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,درخت و درختچه,اصله,49.00
11117,13.02.01.039.08-06.03,13,02,01,039,08,06,03,134.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,پرچین,آبیاری شلنگی,134.00
11118,13.02.01.039.08-01.03,13,02,01,039,08,01,03,690.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,چمن,آبیاری شلنگی,690.00
11119,13.02.01.039.08-02.03,13,02,01,039,08,02,03,788.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,گل دایم باغچه های معمولی,آبیاری شلنگی,788.00

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar">
        <h2>فراخوانی ضرایب</h2>
    </font>  
</div>

In [13]:
raw_coeff = pd.read_excel(
    PROJECT_PATH + r"/assets/input/Landscape_Coefficient_20210318.xlsx",
    sheet_name=None, 
    engine = "openpyxl"
)

# Methods:
#    1. Municipality
#    2.
#    3.
Method_Selected = "Municipality"

raw_coeff.keys()

dict_keys(['Ks', 'Kd', 'Kmc', 'IE', 'PET', 'Effe_Precip'])

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar">
        <h2>تعداد روز در ماه</h2>
    </font>  
</div>

In [14]:
Month_Name = ["M01", "M02", "M03", "M04", "M05", "M06", "M07", "M08", "M09", "M10", "M11", "M12"]

n_Day = [31, 31, 31, 31, 31, 31, 30, 30, 30, 30, 30, 29]

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar">
        <h2>تبخیرتعرق پتانسیل</h2>
    </font>  
</div>

In [15]:
PET = raw_coeff['PET'].set_index('Method').loc[Method_Selected,:].tolist()

display(raw_coeff['PET'].set_index('Method'))

              M01  M02  M03  M04  M05  M06  M07  M08  M09  M10  M11  M12
Method
Municipality 3.83 5.50 7.62 8.74 7.42 5.49 3.34 1.69 1.10 1.04 1.52 2.77

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar">
        <h2>بارش موثر</h2>
    </font>  
</div>

In [16]:
Effe_Precip = raw_coeff['Effe_Precip'].set_index('Method').loc[Method_Selected,:].tolist()

display(raw_coeff['Effe_Precip'].set_index('Method'))

              M01  M02  M03  M04  M05  M06  M07  M08  M09  M10  M11  M12
Method
Municipality 0.23 0.13    0    0    0    0    0    0 0.03 0.07 0.31 0.28

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak">
        <h2>ضرایب</h2>
    </font>  
</div>

<div style="direction:rtl;line-height:300%;" id="section3">
    <font size=3>
        <center>$K_L = K_s * K_d * K_{mc}$</center>    
    </font>
</div>

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak" style="font-size:20px">
         ضرایب از فایل "Coefficient.xlsx" وارد برنامه خواهد شد:
    </font>
</div>

<div style="direction:ltl;line-height:150%;">
    <font face="B Koodak" size=4>
        <b>$K_s$: Species Factor (ضریب گونه)</b>
    </font>  
</div>

In [17]:
Ks = raw_coeff['Ks']

Ks["کد نوع گونه"] = Ks["کد نوع گونه"].astype(str).str.zfill(2)

Ks = pd.melt(
    Ks, 
    id_vars=["نوع گونه", "کد نوع گونه"],
    var_name="ماه",
    value_name="Ks"
)

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak" style="font-size:20px">
         پیش نمایشی از ضریب گونه های مختلف در 12 ماه سال:
    </font>
</div>

In [18]:
display(Ks)

                             نوع گونه کد نوع گونه  ماه   Ks
0                                 چمن          01  M01 0.70
1            گل دایم باغچه های معمولی          02  M01 0.50
2   گل دایم فلاورباکسهای سطوح شیب دار          03  M01 0.50
3             گل فصل باغچه های معمولی          04  M01 0.40
4   گل فصل فلاورباکس های سطوح شیب دار          05  M01 0.40
..                                ...         ...  ...  ...
91            گل فصل باغچه های معمولی          04  M12 0.85
92  گل فصل فلاورباکس های سطوح شیب دار          05  M12 0.85
93                              پرچین          06  M12 0.40
94                      درخت و درختچه          07  M12 0.30
95                       درختان جنگلی          08  M12 0.15

[96 rows x 4 columns]

<div style="direction:ltl;line-height:150%;">
    <font face="B Koodak" size=4>
        <b>$K_d$: Density Factor (ضریب تراکم)</b>
    </font>  
</div>

In [19]:
Kd = raw_coeff['Kd']

Kd["کد نوع گونه"] = Kd["کد نوع گونه"].astype(str).str.zfill(2)

Kd = pd.melt(
    Kd,
    id_vars=["نوع گونه", "کد نوع گونه"],
    var_name="ماه",
    value_name="Kd",
)

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak" style="font-size:20px">
         پیش نمایشی از ضریب تراکم برای گونه های مختلف و لکه های مختلف در 12 ماه سال:
    </font>
</div>

In [20]:
pd.options.display.float_format = "{:,.2f}".format
display(Kd)

                             نوع گونه کد نوع گونه  ماه   Kd
0                                 چمن          01  M01 0.65
1            گل دایم باغچه های معمولی          02  M01 0.75
2   گل دایم فلاورباکسهای سطوح شیب دار          03  M01 0.75
3             گل فصل باغچه های معمولی          04  M01 1.00
4   گل فصل فلاورباکس های سطوح شیب دار          05  M01 1.00
..                                ...         ...  ...  ...
91            گل فصل باغچه های معمولی          04  M12 0.70
92  گل فصل فلاورباکس های سطوح شیب دار          05  M12 0.70
93                              پرچین          06  M12 0.60
94                      درخت و درختچه          07  M12 0.50
95                       درختان جنگلی          08  M12 0.50

[96 rows x 4 columns]

<div style="direction:ltl;line-height:150%;">
    <font face="B Koodak" size=4>
        <b>$K_{mc}$: MicroClimate Factor (ضریب خرد اقلیم)</b>
    </font>  
</div>

In [21]:
Kmc = raw_coeff['Kmc']

Kmc["کد نوع لکه"] = Kmc["کد نوع لکه"].astype(str).str.zfill(2)

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak" style="font-size:20px">
         پیش نمایشی از ضریب خرد اقلیم برای لکه های مختلف:
    </font>
</div>

In [22]:
pd.options.display.float_format = "{:,.2f}".format
display(Kmc)

                       نوع لکه کد نوع لکه  Kmc
0                       میادین         01 1.20
1                      لچکی ها         02 1.20
2            آیلند های بزرگراه         03 1.20
3                     آیلند ها         04 1.20
4            حاشیه های بزرگراه         05 1.30
..                         ...        ...  ...
8   پارک های بین 6 تا 10 هکتار         09 1.00
9      پارک های بالای 10 هکتار         10 1.00
10       جنگل کاری داخل محدوده         11 1.00
11                     کمربندی         12 1.00
12           کمربند سبز حفاظتی         13 1.00

[13 rows x 3 columns]

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak">
        <h2>راندمان آبیاری</h2>
    </font>  
</div>

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak" style="font-size:20px">
         راندمان آبیاری بر اساس روش آبیاری، نوع گونه و نوع لکه متفاوت است.:
    </font>
</div>

In [23]:
IE = raw_coeff['IE']

IE["کد روش آبیاری"] = IE["کد روش آبیاری"].astype(str).str.zfill(2)
IE["کد نوع گونه"] = IE["کد نوع گونه"].astype(str).str.zfill(2)
IE["کد نوع لکه"] = IE["کد نوع لکه"].astype(str).str.zfill(2)

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak" style="font-size:20px">
            پیش نمایشی از راندمان های آبیاری برای شرایط مختلف:
    </font>
</div>

In [24]:
display(IE)

,نوع گونه,کد نوع گونه,روش آبیاری,کد روش آبیاری,نوع لکه,کد نوع لکه,IE
0,چمن,01,آبیاری ثقلی,01,میادین,01,0.60
1,چمن,01,آبیاری ثقلی,01,لچکی ها,02,0.60
2,چمن,01,آبیاری ثقلی,01,آیلند های بزرگراه,03,0.60
3,چمن,01,آبیاری ثقلی,01,آیلند ها,04,0.60
4,چمن,01,آبیاری ثقلی,01,حاشیه های بزرگراه,05,0.60
...,...,...,...,...,...,...,...
437,درختان جنگلی,08,اصله,08,پارک های بین 6 تا 10 هکتار,09,0.55
438,درختان جنگلی,08,اصله,08,پارک های بالای 10 هکتار,10,0.55
439,درختان جنگلی,08,اصله,08,جنگل کاری داخل محدوده,11,0.55
440,درختان جنگلی,08,اصله,08,کمربندی,12,0.55
441,درختان جنگلی,08,اصله,08,کمربند سبز حفاظتی,13,0.55

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak">
        <h2>ترکیب راندمان آبیاری و ضرایب</h2>
    </font>  
</div>

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak" style="font-size:20px">
            برای راحتی استفاده از ضرایب تعریف شده در بالا، همه آن ها در یک متغییر تجمیع می شوند:        
    </font>
</div>

In [25]:
tmp1 = Ks.merge(
    right=Kd,
    how="outer",
    on=["نوع گونه", "کد نوع گونه", "ماه"]
)

tmp2 = IE.merge(
    right=Kmc,
    how="outer",
    on=["نوع لکه", "کد نوع لکه"]
)

Coeff = tmp2.merge(
    right=tmp1,
    how="outer",
    on=["نوع گونه", "کد نوع گونه"]
)

Coeff = Coeff[["نوع لکه",
               "کد نوع لکه",
               "نوع گونه",
               "کد نوع گونه",
               "روش آبیاری",
               "کد روش آبیاری",
               "ماه",
               "Ks",
               "Kd",
               "Kmc",
               "IE"]]

Coeff.columns = ["نام نوع لکه",
                 "نوع لکه",
                 "نام نوع قلم",
                 "نوع قلم",
                 "نام زیرمجموعه هر قلم",
                 "زیرمجموعه هر قلم",
                 "ماه",
                 "Ks",
                 "Kd",
                 "Kmc",
                 "IE"]

Coeff = Coeff.pivot(
    index=["نام نوع لکه", "نوع لکه", "نام نوع قلم", "نوع قلم", "نام زیرمجموعه هر قلم", "زیرمجموعه هر قلم"],
    columns='ماه', 
    values=["Ks", "Kd", "Kmc", "IE"]
).reset_index()

Coeff.columns = ['_'.join(col).strip() for col in Coeff.columns.values]

Coeff.rename(columns={"نام نوع لکه_" : "نام نوع لکه",
                     "نوع لکه_" : "نوع لکه",
                     "نام نوع قلم_" : "نام نوع قلم",
                     "نوع قلم_" : "نوع قلم",
                     "نام زیرمجموعه هر قلم_" : "نام زیرمجموعه هر قلم",
                     "زیرمجموعه هر قلم_" : "زیرمجموعه هر قلم"},
             inplace=True)

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak" style="font-size:20px">
            پیش نمایشی از تجمیع ضرایب برای شرایط مختلف:
    </font>
</div>

In [26]:
display(Coeff)

,نام نوع لکه,نوع لکه,نام نوع قلم,نوع قلم,نام زیرمجموعه هر قلم,زیرمجموعه هر قلم,Ks_M01,Ks_M02,Ks_M03,Ks_M04,Ks_M05,Ks_M06,Ks_M07,Ks_M08,Ks_M09,Ks_M10,Ks_M11,Ks_M12,Kd_M01,Kd_M02,Kd_M03,Kd_M04,Kd_M05,Kd_M06,Kd_M07,Kd_M08,Kd_M09,Kd_M10,Kd_M11,Kd_M12,Kmc_M01,Kmc_M02,Kmc_M03,Kmc_M04,Kmc_M05,Kmc_M06,Kmc_M07,Kmc_M08,Kmc_M09,Kmc_M10,Kmc_M11,Kmc_M12,IE_M01,IE_M02,IE_M03,IE_M04,IE_M05,IE_M06,IE_M07,IE_M08,IE_M09,IE_M10,IE_M11,IE_M12
0,آیلند ها,04,درخت و درختچه,07,آبیاری تانکری,02,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55
1,آیلند ها,04,درخت و درختچه,07,آبیاری تحت فشار,04,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85
2,آیلند ها,04,درخت و درختچه,07,آبیاری ثقلی,01,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60
3,آیلند ها,04,درخت و درختچه,07,آبیاری شلنگی,03,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70
4,آیلند ها,04,درخت و درختچه,07,اصله,08,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,کمربندی,12,گل فصل باغچه های معمولی,04,آبیاری شلنگی,03,0.40,0.40,0.45,0.50,0.50,0.50,0.45,0.40,0.40,0.40,0.40,0.85,1.00,1.00,1.00,1.00,1.00,0.80,0.60,0.60,0.30,0.30,0.30,0.70,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.80,0.80,0.80,0.80,0.80,0.80,0.80,0.80,0.80,0.80,0.80,0.80
438,کمربندی,12,گل فصل فلاورباکس های سطوح شیب دار,05,آبیاری تانکری,02,0.40,0.40,0.45,0.50,0.50,0.50,0.45,0.40,0.40,0.40,0.40,0.85,1.00,1.00,1.00,1.00,1.00,0.80,0.60,0.60,0.30,0.30,0.30,0.70,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55
439,کمربندی,12,گل فصل فلاورباکس های سطوح شیب دار,05,آبیاری تحت فشار,04,0.40,0.40,0.45,0.50,0.50,0.50,0.45,0.40,0.40,0.40,0.40,0.85,1.00,1.00,1.00,1.00,1.00,0.80,0.60,0.60,0.30,0.30,0.30,0.70,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85,0.85
440,کمربندی,12,گل فصل فلاورباکس های سطوح شیب دار,05,آبیاری ثقلی,01,0.40,0.40,0.45,0.50,0.50,0.50,0.45,0.40,0.40,0.40,0.40,0.85,1.00,1.00,1.00,1.00,1.00,0.80,0.60,0.60,0.30,0.30,0.30,0.70,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60
441,کمربندی,12,گل فصل فلاورباکس های سطوح شیب دار,05,آبیاری شلنگی,03,0.40,0.40,0.45,0.50,0.50,0.50,0.45,0.40,0.40,0.40,0.40,0.85,1.00,1.00,1.00,1.00,1.00,0.80,0.60,0.60,0.30,0.30,0.30,0.70,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.80,0.80,0.80,0.80,0.80,0.80,0.80,0.80,0.80,0.80,0.80,0.80

<div style="direction:rtl;line-height:150%;">
    <font face="B Koodak">
        <h2>اضافه کردن ضرایب به دیتابیس</h2>
    </font>  
</div>

In [27]:
Kd_v2 = {
    1: 1,
    2: 1,
    3: 1.2,
    4: 1.2,
    5: 1.3,
    6: 1.3,
    7: 1.3,
    8: 1.3
}

In [28]:
IDs_Asle = ["08", "09"]

dataset_coeff = pd.DataFrame()

for idf, df in dataset.groupby(["منطقه", "ناحیه", "پیمان", "آدرس"]):
    
    if df.query('`زیرمجموعه هر قلم` != @IDs_Asle').shape[0] != 0:        
    
        tmp = df.query('`زیرمجموعه هر قلم` != @IDs_Asle')\
        .groupby(["منطقه", "ناحیه", "پیمان", "آدرس", "نوع قلم"])\
        .apply(lambda x : x['مقدار آیتم'].sum())\
        .reset_index()\
        .rename(columns={0 : "مساحت گونه"})\
        .assign(**{"درصد مساحت گونه در لکه" : lambda x : x['مساحت گونه'] / x['مساحت گونه'].sum()})

        df = df.merge(tmp, how='left', on=["منطقه", "ناحیه", "پیمان", "آدرس", "نوع قلم"])

        df.loc[df["زیرمجموعه هر قلم"] == "08", ["مساحت گونه", "درصد مساحت گونه در لکه"]] = 0
        df.loc[df["زیرمجموعه هر قلم"] == "09", ["مساحت گونه", "درصد مساحت گونه در لکه"]] = 0

        Number_Species = tmp["نوع قلم"].unique().__len__()

        if "08" in list(df["زیرمجموعه هر قلم"]):
            Number_Species += 1

        df["تعداد گونه در لکه"] = Number_Species

        df['Kd_v2'] = list(map(Kd_v2.get, df['تعداد گونه در لکه']))

        df = df.merge(Coeff.drop(["نام نوع لکه", "نام نوع قلم", "نام زیرمجموعه هر قلم"], axis=1),
                      how="left",
                      on=["نوع لکه", "نوع قلم", "زیرمجموعه هر قلم"])
        
        
#         for index, row in df.iterrows():
#             if row['نوع قلم'] == "07":
#                 if row['زیرمجموعه هر قلم'] != "08" and row['زیرمجموعه هر قلم'] != "09":
#                     tree_Area = row['مقدار آیتم'] / row['مقدار آیتم خام']
#                     if tree_Area == 9:
#                         df.loc[index, 'Kd_M01'] = 0.52
#                         df.loc[index, 'Kd_M02'] = 0.52
#                         df.loc[index, 'Kd_M03'] = 0.52
#                         df.loc[index, 'Kd_M04'] = 0.52
#                         df.loc[index, 'Kd_M05'] = 0.52
#                         df.loc[index, 'Kd_M06'] = 0.52
#                         df.loc[index, 'Kd_M07'] = 0.52
#                         df.loc[index, 'Kd_M08'] = 0.52
#                         df.loc[index, 'Kd_M09'] = 0.52
#                         df.loc[index, 'Kd_M10'] = 0.52
#                         df.loc[index, 'Kd_M11'] = 0.52
#                         df.loc[index, 'Kd_M12'] = 0.52
#                     else:
#                         df.loc[index, 'Kd_M01'] = 0.65
#                         df.loc[index, 'Kd_M02'] = 0.65
#                         df.loc[index, 'Kd_M03'] = 0.65
#                         df.loc[index, 'Kd_M04'] = 0.65
#                         df.loc[index, 'Kd_M05'] = 0.65
#                         df.loc[index, 'Kd_M06'] = 0.65
#                         df.loc[index, 'Kd_M07'] = 0.65
#                         df.loc[index, 'Kd_M08'] = 0.65
#                         df.loc[index, 'Kd_M09'] = 0.65
#                         df.loc[index, 'Kd_M10'] = 0.65
#                         df.loc[index, 'Kd_M11'] = 0.65
#                         df.loc[index, 'Kd_M12'] = 0.65

        dataset_coeff = pd.concat([dataset_coeff, df])
        
    else:
        df["مساحت گونه"] = df["مقدار آیتم"] * 9
        df = df.assign(**{"درصد مساحت گونه در لکه" : 1})
        df = df.assign(**{"تعداد گونه در لکه" : 1})
        df = df.assign(**{"Kd_v2" : list(map(Kd_v2.get, df['تعداد گونه در لکه']))})
        
        df = df.merge(Coeff.drop(["نام نوع لکه", "نام نوع قلم", "نام زیرمجموعه هر قلم"], axis=1),
                      how="left",
                      on=["نوع لکه", "نوع قلم", "زیرمجموعه هر قلم"])
        
        dataset_coeff = pd.concat([dataset_coeff, df])

dataset_coeff = dataset_coeff.reset_index(drop=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\
C:\Users\ASUS\AppData\Local\Temp\ipykernel_1256\1818053422.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x : x['مقدار آیتم'].sum())\

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar" style="font-size:20px">
            پیش نمایشی از اضافه کردن ضرایب به دیتابیس:
    </font>
</div>

In [29]:
dataset_coeff.query('منطقه == "01"').query('ناحیه == "02"').query('پیمان == "02"').query('آدرس == "035"')

,شناسه,منطقه,ناحیه,پیمان,آدرس,نوع لکه,نوع قلم,زیرمجموعه هر قلم,مقدار آیتم,مساحت آدرس,مساحت پیمان,نوع آیتم,نام پیمان,نام لکه,نام نوع لکه,نام نوع قلم,نام زیرمجموعه هر قلم,مقدار آیتم خام,مساحت گونه,درصد مساحت گونه در لکه,تعداد گونه در لکه,Kd_v2,Ks_M01,Ks_M02,Ks_M03,Ks_M04,Ks_M05,Ks_M06,Ks_M07,Ks_M08,Ks_M09,Ks_M10,Ks_M11,Ks_M12,Kd_M01,Kd_M02,Kd_M03,Kd_M04,Kd_M05,Kd_M06,Kd_M07,Kd_M08,Kd_M09,Kd_M10,Kd_M11,Kd_M12,Kmc_M01,Kmc_M02,Kmc_M03,Kmc_M04,Kmc_M05,Kmc_M06,Kmc_M07,Kmc_M08,Kmc_M09,Kmc_M10,Kmc_M11,Kmc_M12,IE_M01,IE_M02,IE_M03,IE_M04,IE_M05,IE_M06,IE_M07,IE_M08,IE_M09,IE_M10,IE_M11,IE_M12
798,01.02.02.035.06-07.08,01,02,02,035,06,07,08,516.00,838.00,"111,069.00",ریزآیتمی,ب ناحیه 2 منطقه 1 - 9808,خیابان جامی,حاشیه معابر,درخت و درختچه,اصله,516.00,0.00,0.00,3,1.20,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55
799,01.02.02.035.06-07.02,01,02,02,035,06,07,02,61.71,838.00,"111,069.00",ریزآیتمی,ب ناحیه 2 منطقه 1 - 9808,خیابان جامی,حاشیه معابر,درخت و درختچه,آبیاری تانکری,38.00,267.97,0.28,3,1.20,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55
800,01.02.02.035.06-07.03,01,02,02,035,06,07,03,206.25,838.00,"111,069.00",ریزآیتمی,ب ناحیه 2 منطقه 1 - 9808,خیابان جامی,حاشیه معابر,درخت و درختچه,آبیاری شلنگی,127.00,267.97,0.28,3,1.20,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70
801,01.02.02.035.06-06.02,01,02,02,035,06,06,02,673.00,838.00,"111,069.00",ریزآیتمی,ب ناحیه 2 منطقه 1 - 9808,خیابان جامی,حاشیه معابر,پرچین,آبیاری تانکری,673.00,673.00,0.72,3,1.20,0.50,0.60,0.75,0.80,0.80,0.80,0.75,0.70,0.40,0.35,0.35,0.40,0.70,0.80,0.90,1.00,1.00,1.00,0.90,0.85,0.65,0.65,0.50,0.60,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55
802,01.02.02.035.06-07.09,01,02,02,035,06,07,09,165.00,838.00,"111,069.00",ریزآیتمی,ب ناحیه 2 منطقه 1 - 9808,خیابان جامی,حاشیه معابر,درخت و درختچه,اصله مستقل,165.00,0.00,0.00,3,1.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar">
        <h2>اضافه کردن تبخیرتعرق پتانسیل و بارش موثر به دیتاست</h2>
    </font>  
</div>

In [30]:
for i, value in enumerate(Month_Name):    
    dataset_coeff["PET_" + value] = PET[i]
    
for i, value in enumerate(Month_Name):   
    dataset_coeff["Effe_Precip_" + value] = Effe_Precip[i]

for i, value in enumerate(Month_Name):
    dataset_coeff["n_Day_" + value] = n_Day[i]

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar" style="font-size:20px">
            پیش نمایشی از اضافه کردن ضرایب به دیتاست:
    </font>
</div>

In [31]:
dataset_coeff

,شناسه,منطقه,ناحیه,پیمان,آدرس,نوع لکه,نوع قلم,زیرمجموعه هر قلم,مقدار آیتم,مساحت آدرس,مساحت پیمان,نوع آیتم,نام پیمان,نام لکه,نام نوع لکه,نام نوع قلم,نام زیرمجموعه هر قلم,مقدار آیتم خام,مساحت گونه,درصد مساحت گونه در لکه,تعداد گونه در لکه,Kd_v2,Ks_M01,Ks_M02,Ks_M03,Ks_M04,Ks_M05,Ks_M06,Ks_M07,Ks_M08,Ks_M09,Ks_M10,Ks_M11,Ks_M12,Kd_M01,Kd_M02,Kd_M03,Kd_M04,Kd_M05,Kd_M06,Kd_M07,Kd_M08,Kd_M09,Kd_M10,Kd_M11,Kd_M12,Kmc_M01,Kmc_M02,Kmc_M03,Kmc_M04,Kmc_M05,Kmc_M06,Kmc_M07,Kmc_M08,Kmc_M09,Kmc_M10,Kmc_M11,Kmc_M12,IE_M01,IE_M02,IE_M03,IE_M04,IE_M05,IE_M06,IE_M07,IE_M08,IE_M09,IE_M10,IE_M11,IE_M12,PET_M01,PET_M02,PET_M03,PET_M04,PET_M05,PET_M06,PET_M07,PET_M08,PET_M09,PET_M10,PET_M11,PET_M12,Effe_Precip_M01,Effe_Precip_M02,Effe_Precip_M03,Effe_Precip_M04,Effe_Precip_M05,Effe_Precip_M06,Effe_Precip_M07,Effe_Precip_M08,Effe_Precip_M09,Effe_Precip_M10,Effe_Precip_M11,Effe_Precip_M12,n_Day_M01,n_Day_M02,n_Day_M03,n_Day_M04,n_Day_M05,n_Day_M06,n_Day_M07,n_Day_M08,n_Day_M09,n_Day_M10,n_Day_M11,n_Day_M12
0,01.01.01.001.04-07.08,01,01,01,001,04,07,08,365.00,"2,718.00","122,306.00",ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,درخت و درختچه,اصله,365.00,0.00,0.00,5,1.30,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29
1,01.01.01.001.04-06.03,01,01,01,001,04,06,03,299.00,"2,718.00","122,306.00",ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,پرچین,آبیاری شلنگی,299.00,"1,704.00",0.63,5,1.30,0.50,0.60,0.75,0.80,0.80,0.80,0.75,0.70,0.40,0.35,0.35,0.40,0.70,0.80,0.90,1.00,1.00,1.00,0.90,0.85,0.65,0.65,0.50,0.60,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29
2,01.01.01.001.04-06.02,01,01,01,001,04,06,02,"1,405.00","2,718.00","122,306.00",ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,پرچین,آبیاری تانکری,"1,405.00","1,704.00",0.63,5,1.30,0.50,0.60,0.75,0.80,0.80,0.80,0.75,0.70,0.40,0.35,0.35,0.40,0.70,0.80,0.90,1.00,1.00,1.00,0.90,0.85,0.65,0.65,0.50,0.60,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29
3,01.01.01.001.04-01.03,01,01,01,001,04,01,03,784.00,"2,718.00","122,306.00",ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,چمن,آبیاری شلنگی,784.00,784.00,0.29,5,1.30,0.70,0.75,0.80,0.90,0.90,0.80,0.75,0.70,0.50,0.50,0.50,0.55,0.65,0.70,0.70,0.80,0.80,0.80,0.80,0.70,0.50,0.40,0.40,0.60,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29
4,01.01.01.001.04-02.03,01,01,01,001,04,02,03,210.00,"2,718.00","122,306.00",ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,گل دایم باغچه های معمولی,آبیاری شلنگی,210.00,210.00,0.08,5,1.30,0.50,0.60,0.65,0.70,0.70,0.65,0.60,0.50,0.40,0.35,0.35,0.40,0.75,0.85,0.90,1.00,1.00,1.00,0.90,0.80,0.70,0.50,0.50,0.60,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,1.20,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11115,13.02.01.038.08-04.03,13,02,01,038,08,04,03,14.00,"1,174.70","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک سارا,پارک های زیر 6 هکتار,گل فصل باغچه های معمولی,آبیاری شلنگی,14.00,14.00,0.02,5,1.30,0.40,0.40,0.45,0.50,0.50,0.50,0.45,0.40,0.40,0.40,0.40,0.85,1.00,1.00,1.00,1.00,1.00,0.80,0.60,0.60,0.30,0.30,0.30,0.70,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29
11116,13.02.01.039.08-07.08,13,02,01,039,08,07,08,49.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,درخت و درختچه,اصله,49.00,0.00,0.00,4,1.20,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29
11117,13.02.01.039.08-06.03,13,02,01,039,08,06,03,134.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,پرچین,آبیاری شلنگی,134.00,134.00,0.08,4,1.20,0.50,0.60,0.75,0.80,0.80,0.80,0.75,0.70,0.40,0.35,0.35,0.40,0.70,0.80,0.90,1.00,1.00,1.00,0.90,0.85,0.65,0.65,0.50,0.60,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29
11118,13.02.01.039.08-01.03,13,02,01,039,08,01,03,690.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,چمن,آبیاری شلنگی,690.00,690.00,0.43,4,1.20,0.70,0.75,0.80,0.90,0.90,0.80,0.75,0.70,0.50,0.50,0.50,0.55,0.65,0.70,0.70,0.80,0.80,0.80,0.80,0.70,0.50,0.40,0.40,0.60,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29
11119,13.02.01.039.08-02.03,13,02,01,039,08,02,03,788.00,"2,233.00","66,059.70",ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,گل دایم باغچه های معمولی,آبیاری شلنگی,788.00,788.00,0.49,4,1.20,0.50,0.60,0.65,0.70,0.70,0.65,0.60,0.50,0.40,0.35,0.35,0.40,0.75,0.85,0.90,1.00,1.00,1.00,0.90,0.80,0.70,0.50,0.50,0.60,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar">
        <h2>محاسبه تبخیرتعرق فضای سبز و نیاز آبی</h2>
    </font>  
</div>

<div style="direction:rtl;line-height:300%;" id="section3">
    <font size=3>
        <center>$LET = PET * K_s * K_d * K_{mc}$</center>
        <center>$IR = \frac{LET - Eff.Precip}{IE} * Area$</center> 
    </font>
</div>

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar">
        <h3>روش اول (حمید عمرانیان)</h3>
    </font>  
</div>

In [34]:
result_method_01 = dataset_coeff.copy()

for i, value in enumerate(Month_Name):    
    result_method_01["KL_" + value] = result_method_01["Ks_" + value] * result_method_01["Kd_" + value] * result_method_01["Kmc_" + value]

for i, value in enumerate(Month_Name):    
    result_method_01["LET_" + value] = result_method_01["PET_" + value] * result_method_01["KL_" + value]

for i, value in enumerate(Month_Name):
    result_method_01["IR_" + value] = ((result_method_01["LET_" + value] - result_method_01["Effe_Precip_" + value]) * result_method_01["n_Day_" + value] / result_method_01["IE_" + value]) * result_method_01["مقدار آیتم"] / 1000
    result_method_01.loc[result_method_01["IR_" + value] < 0, ["IR_" + value]] = 0

result_method_01["IR"] = result_method_01[["IR_M01", "IR_M02", "IR_M03", "IR_M04", "IR_M05", "IR_M06", "IR_M07", "IR_M08", "IR_M09", "IR_M10", "IR_M11", "IR_M12"]].sum(axis=1)

date = datetime.today().strftime('%Y%m%d')
file_name = PROJECT_PATH + r"/assets/report/mspl_method_" + date + ".xlsx"
with pd.ExcelWriter(path=file_name, engine="openpyxl", mode="w") as writer:
    result_method_01.to_excel(writer, index=False, sheet_name="نتایج کلی")

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar" style="font-size:20px">
            پیش نمایشی از نتایج روش اول:
    </font>
</div>

In [35]:
pd.options.display.max_rows = 6
pd.options.display.float_format = "{:,.2f}".format
result_method_01.query('منطقه == "06"').query('ناحیه == "02"').query('پیمان == "01"').query('آدرس == "014"')

,شناسه,منطقه,ناحیه,پیمان,آدرس,نوع لکه,نوع قلم,زیرمجموعه هر قلم,مقدار آیتم,مساحت آدرس,مساحت پیمان,نوع آیتم,نام پیمان,نام لکه,نام نوع لکه,نام نوع قلم,نام زیرمجموعه هر قلم,مقدار آیتم خام,مساحت گونه,درصد مساحت گونه در لکه,تعداد گونه در لکه,Kd_v2,Ks_M01,Ks_M02,Ks_M03,Ks_M04,Ks_M05,Ks_M06,Ks_M07,Ks_M08,Ks_M09,Ks_M10,Ks_M11,Ks_M12,Kd_M01,Kd_M02,Kd_M03,Kd_M04,Kd_M05,Kd_M06,Kd_M07,Kd_M08,Kd_M09,Kd_M10,Kd_M11,Kd_M12,Kmc_M01,Kmc_M02,Kmc_M03,Kmc_M04,Kmc_M05,Kmc_M06,Kmc_M07,Kmc_M08,Kmc_M09,Kmc_M10,Kmc_M11,Kmc_M12,IE_M01,IE_M02,IE_M03,IE_M04,IE_M05,IE_M06,IE_M07,IE_M08,IE_M09,IE_M10,IE_M11,IE_M12,PET_M01,PET_M02,PET_M03,PET_M04,PET_M05,PET_M06,PET_M07,PET_M08,PET_M09,PET_M10,PET_M11,PET_M12,Effe_Precip_M01,Effe_Precip_M02,Effe_Precip_M03,Effe_Precip_M04,Effe_Precip_M05,Effe_Precip_M06,Effe_Precip_M07,Effe_Precip_M08,Effe_Precip_M09,Effe_Precip_M10,Effe_Precip_M11,Effe_Precip_M12,n_Day_M01,n_Day_M02,n_Day_M03,n_Day_M04,n_Day_M05,n_Day_M06,n_Day_M07,n_Day_M08,n_Day_M09,n_Day_M10,n_Day_M11,n_Day_M12,KL_M01,KL_M02,KL_M03,KL_M04,KL_M05,KL_M06,KL_M07,KL_M08,KL_M09,KL_M10,KL_M11,KL_M12,LET_M01,LET_M02,LET_M03,LET_M04,LET_M05,LET_M06,LET_M07,LET_M08,LET_M09,LET_M10,LET_M11,LET_M12,IR_M01,IR_M02,IR_M03,IR_M04,IR_M05,IR_M06,IR_M07,IR_M08,IR_M09,IR_M10,IR_M11,IR_M12,IR
4541,06.02.01.014.06-07.08,06,02,01,014,06,07,08,71.00,213.00,"280,726.00",ریزآیتمی,الف ناحیه 2 منطقه 6 - 9808,حاشیه بلوار بصیرت,حاشیه معابر,درخت و درختچه,اصله,71.00,639.00,1.00,1,1.00,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,1.30,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29,0.29,0.33,0.43,0.47,0.47,0.47,0.33,0.26,0.16,0.16,0.16,0.20,1.12,1.79,3.27,4.09,3.47,2.57,1.08,0.44,0.18,0.17,0.25,0.54,3.54,6.65,13.08,16.37,13.90,10.27,4.20,1.70,0.59,0.39,0.00,0.97,71.66

<div style="direction:rtl;line-height:150%;">
    <font face="B Zar" style="font-size:20px">
            مساحت فضای سبز و نیاز آبی گونه های مختلف:
    </font>
</div>

In [39]:
IDs_Asle = ["08", "09"]

df = result_method_01[["منطقه", "ناحیه", "پیمان", "آدرس", "نوع لکه", "نوع قلم", "زیرمجموعه هر قلم", "مقدار آیتم", "IR", "IR_M04", "نام نوع قلم", "نام زیرمجموعه هر قلم"]]

df = df.query('`زیرمجموعه هر قلم` != @IDs_Asle').reset_index()

result = df.pivot_table(
    values=["مقدار آیتم", "IR", "IR_M04"],
    index=["منطقه", "ناحیه"],
#     columns=["نام نوع قلم", "نام زیرمجموعه هر قلم"],
    aggfunc={"مقدار آیتم": "sum",
            "IR": "sum",
            "IR_M04" : "sum"},
#     margins=True,
#     margins_name="جمع کل",
).fillna(0).reset_index(drop=False)


result['IR'] = result['IR'] / 1000
result['IR_M04'] = result['IR_M04'] / 1000
result['مقدار آیتم'] = result['مقدار آیتم'] / 10000

result = result.rename(columns={'IR' : 'نیاز آب آبیاری سالانه',
                                'IR_M04' : 'نیاز آب آبیاری تیر ماه',
                                'مقدار آیتم' : 'مساحت'})

file_name = PROJECT_PATH + r"/assets/report/mspl_method_" + date + ".xlsx"
with pd.ExcelWriter(path=file_name, engine="openpyxl", mode="a") as writer:
    result.to_excel(writer, index=False, sheet_name="مساحت - منطقه - ناحیه")
    
display(result)

   منطقه ناحیه  نیاز آب آبیاری سالانه  نیاز آب آبیاری تیر ماه  مساحت
0     01    01                 149.69                   34.43  10.97
1     01    02                 324.53                   74.70  24.74
2     01    03                 117.95                   27.20   8.16
..   ...   ...                    ...                     ...    ...
35    12    03                 169.82                   39.06  18.05
36    13    01                  45.44                   10.48   3.11
37    13    02                  61.91                   14.27   5.24

[38 rows x 5 columns]

In [40]:
IDs_Asle = ["08", "09"]

df = result_method_01[["منطقه", "ناحیه", "پیمان", "آدرس", "نوع لکه", "نوع قلم", "زیرمجموعه هر قلم", "مقدار آیتم", "IR", "IR_M04", "نام نوع قلم", "نام زیرمجموعه هر قلم"]]

df = df.query('`زیرمجموعه هر قلم` != @IDs_Asle').reset_index()

result = df.pivot_table(
    values=["مقدار آیتم", "IR", "IR_M04"],
    index=["منطقه"],
#     columns=["نام نوع قلم", "نام زیرمجموعه هر قلم"],
    aggfunc={"مقدار آیتم": "sum",
            "IR": "sum",
            "IR_M04" : "sum"},
#     margins=True,
#     margins_name="جمع کل",
).fillna(0).reset_index(drop=False)


result['IR'] = result['IR'] / 1000
result['IR_M04'] = result['IR_M04'] / 1000
result['مقدار آیتم'] = result['مقدار آیتم'] / 10000

result = result.rename(columns={'IR' : 'نیاز آب آبیاری سالانه',
                                'IR_M04' : 'نیاز آب آبیاری تیر ماه',
                                'مقدار آیتم' : 'مساحت'})

file_name = PROJECT_PATH + r"/assets/report/mspl_method_" + date + ".xlsx"
with pd.ExcelWriter(path=file_name, engine="openpyxl", mode="a") as writer:
    result.to_excel(writer, index=False, sheet_name="مساحت - منطقه")
    
display(result)

   منطقه  نیاز آب آبیاری سالانه  نیاز آب آبیاری تیر ماه  مساحت
0     01                 592.17                  136.33  43.87
1     02               1,416.37                  325.72 124.18
2     03               1,110.37                  255.94 102.82
..   ...                    ...                     ...    ...
10    11               1,439.04                  331.01 128.95
11    12                 907.73                  208.60  92.65
12    13                 107.34                   24.75   8.35

[13 rows x 4 columns]

In [41]:
IDs_Asle = ["08", "09"]

df = result_method_01[["منطقه", "ناحیه", "پیمان", "آدرس", "نوع لکه", "نوع قلم", "زیرمجموعه هر قلم", "مقدار آیتم", "IR", "IR_M04", "نام نوع قلم", "نام زیرمجموعه هر قلم", "نام لکه"]]

df = df.query('`زیرمجموعه هر قلم` != @IDs_Asle').reset_index()

result = df.pivot_table(
    values=["مقدار آیتم", "IR", "IR_M04"],
    index=["منطقه", "ناحیه", "نام لکه"],
#     columns=["نام نوع قلم", "نام زیرمجموعه هر قلم"],
    aggfunc={"مقدار آیتم": "sum",
            "IR": "sum",
            "IR_M04" : "sum"},
#     margins=True,
#     margins_name="جمع کل",
).fillna(0).reset_index(drop=False)


result['IR'] = result['IR'] / 1000
result['IR_M04'] = result['IR_M04'] / 1000
result['مقدار آیتم'] = result['مقدار آیتم'] / 10000

result = result.rename(columns={'IR' : 'نیاز آب آبیاری سالانه',
                                'IR_M04' : 'نیاز آب آبیاری تیر ماه',
                                'مقدار آیتم' : 'مساحت'})

file_name = PROJECT_PATH + r"/assets/report/mspl_method_" + date + ".xlsx"
with pd.ExcelWriter(path=file_name, engine="openpyxl", mode="a") as writer:
    result.to_excel(writer, index=False, sheet_name="مساحت - منطقه - لکه")
    
display(result)

,منطقه,ناحیه,نام لکه,نیاز آب آبیاری سالانه,نیاز آب آبیاری تیر ماه,مساحت
0,01,01,آیلند بلوار ابوذر و لچکی ها,4.81,1.11,0.27
1,01,01,آیلند بلوار احمد آباد,21.74,4.97,1.82
2,01,01,آیلند بلوار بعثت,4.75,1.09,0.32
...,...,...,...,...,...,...
2289,13,02,پارک ره باغ بهشت,4.68,1.08,0.48
2290,13,02,پارک سارا,1.05,0.24,0.08
2291,13,02,پارک پردیس,1.93,0.45,0.16

In [45]:
result_method_01[result_method_01["نام لکه"] == "جنگل زنبق"]

,شناسه,منطقه,ناحیه,پیمان,آدرس,نوع لکه,نوع قلم,زیرمجموعه هر قلم,مقدار آیتم,مساحت آدرس,مساحت پیمان,نوع آیتم,نام پیمان,نام لکه,نام نوع لکه,نام نوع قلم,نام زیرمجموعه هر قلم,مقدار آیتم خام,مساحت گونه,درصد مساحت گونه در لکه,تعداد گونه در لکه,Kd_v2,Ks_M01,Ks_M02,Ks_M03,Ks_M04,Ks_M05,Ks_M06,Ks_M07,Ks_M08,Ks_M09,Ks_M10,Ks_M11,Ks_M12,Kd_M01,Kd_M02,Kd_M03,Kd_M04,Kd_M05,Kd_M06,Kd_M07,Kd_M08,Kd_M09,Kd_M10,Kd_M11,Kd_M12,Kmc_M01,Kmc_M02,Kmc_M03,Kmc_M04,Kmc_M05,Kmc_M06,Kmc_M07,Kmc_M08,Kmc_M09,Kmc_M10,Kmc_M11,Kmc_M12,IE_M01,IE_M02,IE_M03,IE_M04,IE_M05,IE_M06,IE_M07,IE_M08,IE_M09,IE_M10,IE_M11,IE_M12,PET_M01,PET_M02,PET_M03,PET_M04,PET_M05,PET_M06,PET_M07,PET_M08,PET_M09,PET_M10,PET_M11,PET_M12,Effe_Precip_M01,Effe_Precip_M02,Effe_Precip_M03,Effe_Precip_M04,Effe_Precip_M05,Effe_Precip_M06,Effe_Precip_M07,Effe_Precip_M08,Effe_Precip_M09,Effe_Precip_M10,Effe_Precip_M11,Effe_Precip_M12,n_Day_M01,n_Day_M02,n_Day_M03,n_Day_M04,n_Day_M05,n_Day_M06,n_Day_M07,n_Day_M08,n_Day_M09,n_Day_M10,n_Day_M11,n_Day_M12,KL_M01,KL_M02,KL_M03,KL_M04,KL_M05,KL_M06,KL_M07,KL_M08,KL_M09,KL_M10,KL_M11,KL_M12,LET_M01,LET_M02,LET_M03,LET_M04,LET_M05,LET_M06,LET_M07,LET_M08,LET_M09,LET_M10,LET_M11,LET_M12,IR_M01,IR_M02,IR_M03,IR_M04,IR_M05,IR_M06,IR_M07,IR_M08,IR_M09,IR_M10,IR_M11,IR_M12,IR
7551,09.03.01.042.11-07.08,09,03,01,042,11,07,08,540.00,"3,640.00","287,973.00",ریزآیتمی,الف ناحیه 3 منطقه 9,جنگل زنبق,جنگل کاری داخل محدوده,درخت و درختچه,اصله,540.00,0.00,0.00,2,1.00,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,0.55,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29,0.23,0.25,0.33,0.36,0.36,0.36,0.25,0.20,0.12,0.12,0.12,0.15,0.86,1.37,2.51,3.15,2.67,1.97,0.83,0.34,0.14,0.13,0.19,0.42,19.07,38.00,76.52,95.75,81.33,60.10,24.56,9.95,3.25,1.86,0.00,3.82,414.22
7552,09.03.01.042.11-07.03,09,03,01,042,11,07,03,"2,224.44","3,640.00","287,973.00",ریزآیتمی,الف ناحیه 3 منطقه 9,جنگل زنبق,جنگل کاری داخل محدوده,درخت و درختچه,آبیاری شلنگی,330.00,"3,640.00",1.00,2,1.00,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,0.70,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29,0.23,0.25,0.33,0.36,0.36,0.36,0.25,0.20,0.12,0.12,0.12,0.15,0.86,1.37,2.51,3.15,2.67,1.97,0.83,0.34,0.14,0.13,0.19,0.42,61.73,122.98,247.68,309.91,263.24,194.53,79.49,32.20,10.53,6.01,0.00,12.37,"1,340.67"
7553,09.03.01.042.11-07.01,09,03,01,042,11,07,01,"1,415.56","3,640.00","287,973.00",ریزآیتمی,الف ناحیه 3 منطقه 9,جنگل زنبق,جنگل کاری داخل محدوده,درخت و درختچه,آبیاری ثقلی,"1,530.00","3,640.00",1.00,2,1.00,0.45,0.50,0.55,0.60,0.60,0.60,0.50,0.40,0.25,0.25,0.25,0.30,0.50,0.50,0.60,0.60,0.60,0.60,0.50,0.50,0.50,0.50,0.50,0.50,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,0.60,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29,0.23,0.25,0.33,0.36,0.36,0.36,0.25,0.20,0.12,0.12,0.12,0.15,0.86,1.37,2.51,3.15,2.67,1.97,0.83,0.34,0.14,0.13,0.19,0.42,45.83,91.30,183.88,230.08,195.44,144.43,59.02,23.90,7.82,4.46,0.00,9.18,995.35
7554,09.03.01.042.11-07.09,09,03,01,042,11,07,09,540.00,"3,640.00","287,973.00",ریزآیتمی,الف ناحیه 3 منطقه 9,جنگل زنبق,جنگل کاری داخل محدوده,درخت و درختچه,اصله مستقل,540.00,0.00,0.00,2,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.83,5.50,7.62,8.74,7.42,5.49,3.34,1.69,1.10,1.04,1.52,2.77,0.23,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.07,0.31,0.28,31,31,31,31,31,31,30,30,30,30,30,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00

In [46]:
df_final = result_method_01.copy()

In [50]:
df_final.head(2).to_clipboard()

In [47]:
df_final.to_excel(PROJECT_PATH + r"/assets/report/final" + date + "_final.xlsx", index=False, sheet_name="نتایج کلی")

#تست اضافه کردن

In [44]:
import geopandas as gpd
from datetime import datetime

# ۱. یک کپی از دیتابیس می‌گیریم تا فایل اصلی دست‌نخورده بماند
df_final = result_method_01.copy()

# ۲. ساختن یک "شناسه" در اکسل (دقیقاً مشابه منطقی که برای QGIS نوشتی)
df_final["شناسه_تطبیق"] = "1" + df_final["منطقه"] + df_final["ناحیه"] + df_final["پیمان"] + "-" + df_final["نام لکه"]

# ۳. فراخوانی شیپ‌فایل "وضع موجود" و آماده‌سازی شناسه‌های آن
qgis_shapefile = gpd.read_file("../assets/input/GIS_Layer/Mashhad_Landscape_Existed_20210319.shp")

qgis_shapefile["Code_Bank"] = qgis_shapefile["Code_Bank"].apply(lambda x : str(x)[0:6])
qgis_shapefile["Code_Bank"] = "1" + qgis_shapefile["Code_Bank"]

qgis_shapefile["Name_Bank"] = qgis_shapefile["Name_Bank"].str.replace('ي','ی')
qgis_shapefile["Name_Bank"] = qgis_shapefile["Name_Bank"].str.replace('ئ','ی')
qgis_shapefile["Name_Bank"] = qgis_shapefile["Name_Bank"].str.strip()

def change_peyman(x):
    peyman = {
        '1020201' : '1020202', '1020202' : '1020201', '1050101' : '1050102', '1050102' : '1050101',
        '1070203' : '1070204', '1070204' : '1070203', '1080201' : '1080202', '1080202' : '1080201',
        '1090103' : '1090104', '1090104' : '1090103', '1090302' : '1090303', '1090303' : '1090302',
        '1000000' : ''
    }
    if x in list(peyman.keys()):
        return peyman[x]
    else:
        return x

qgis_shapefile["Code_Bank"] = qgis_shapefile["Code_Bank"].apply(lambda x : change_peyman(x))
qgis_shapefile["شناسه_شپ"] = qgis_shapefile["Code_Bank"] + "-" + qgis_shapefile["Name_Bank"]

# ۴. گرفتن لیست تمام شناسه‌هایی که در نقشه "وضع موجود" هستند
existed_spots = qgis_shapefile["شناسه_شپ"].unique().tolist()

# ۵. ساخت ستون جدید: اگر شناسه اکسل در شیپ‌فایل بود -> وضع موجود، در غیر این‌صورت -> تفصیلی
df_final['وضعیت_لکه'] = df_final['شناسه_تطبیق'].apply(lambda x: 'وضع موجود' if x in existed_spots else 'تفصیلی')

# پاک کردن ستون موقتی که فقط برای تطبیق ساخته بودیم
df_final = df_final.drop(columns=['شناسه_تطبیق'])

# ۶. ذخیره کل دیتابیس (بدون کم شدن حتی یک ستون) در یک فایل اکسل
date = datetime.today().strftime('%Y%m%d')
file_name = PROJECT_PATH + "assets/report/result_method_01_with_status_" + date + ".xlsx"

with pd.ExcelWriter(path=file_name, engine="openpyxl", mode="w") as writer:
    df_final.to_excel(writer, index=False, sheet_name="دیتابیس کل")

OSError: Cannot save file into a non-existent directory: 'C:\thesis\Shirazi_Code\Landscape_Evapotranspirationassets\report'

# Export for QGIS - Existed Layer

In [43]:

IDs_Asle = ["08", "09"]

df = result_method_01[[
    "منطقه", 
    "ناحیه", 
    "پیمان", 
    "آدرس",
    "نام لکه",
    "نوع لکه",
    "نام نوع لکه",
    "نوع قلم",
    "نام نوع قلم",
    "زیرمجموعه هر قلم",
    "نام زیرمجموعه هر قلم",
    "مقدار آیتم",
    "IR",
    "IR_M04"
]]

df = df.query('`زیرمجموعه هر قلم` != @IDs_Asle').reset_index()

Area_Method_01 = df.pivot_table(
    values=["مقدار آیتم"],
    index=["منطقه", "ناحیه", "پیمان", "آدرس", "نام لکه", "نام نوع لکه"],
    aggfunc={
        "مقدار آیتم": "sum"
    },
).fillna(0).reset_index(drop=False)

IR_Method_01 = df.pivot_table(
    values=["IR", "IR_M04"],
    index=["منطقه", "ناحیه", "پیمان", "آدرس", "نام لکه", "نام نوع لکه"],
    aggfunc={
        "IR": "sum",
        "IR_M04" : "sum"
    },
).fillna(0).reset_index(drop=False)

Output_Method_01 = pd.merge(
    left=Area_Method_01,
    right=IR_Method_01,
    how='outer',
    on=["منطقه", "ناحیه", "پیمان", "آدرس", "نام لکه", "نام نوع لکه"]
)

Output_Method_01.columns = ["منطقه", 
                            "ناحیه", 
                            "پیمان", 
                            "آدرس", 
                            "نام لکه", 
                            "نام نوع لکه",
                            "مساحت", 
                            "نیاز آبی سالانه", 
                            "نیاز آبی تیر ماه"]

# qgis_result["هیدرومودول"] = qgis_result["نیاز آبی تیر ماه"] / qgis_result["مساحت"]

Output_Method_01["شناسه"] = "1" + Output_Method_01["منطقه"] + Output_Method_01["ناحیه"] + Output_Method_01["پیمان"] + "-" + Output_Method_01["نام لکه"]

Output_Method_01 = Output_Method_01[["شناسه", 
                                     "مساحت", 
                                     "نیاز آبی سالانه", 
                                     "نیاز آبی تیر ماه", 
                                     "نام نوع لکه"]]




# qgis_shapefile = pd.read_excel(
#     PROJECT_PATH + "assets/data/All_Existed_20210104.xlsx",
#     dtype={
#         "Code_Bank": str
#     },
#     engine = "openpyxl",
#     na_filter=False
# )

qgis_shapefile = gpd.read_file("../assets/input/GIS_Layer/Mashhad_Landscape_Existed_20210319.shp")

qgis_shapefile["Code_Bank"] = qgis_shapefile["Code_Bank"].apply(lambda x : x[0:6])
qgis_shapefile["Code_Bank"] = "1" + qgis_shapefile["Code_Bank"]
# qgis_shapefile["Code_Bank"] = qgis_shapefile["Code_Bank"].apply(lambda x : x[:-3])


qgis_shapefile["Name_Bank"] = qgis_shapefile["Name_Bank"].str.replace('ي','ی')
qgis_shapefile["Name_Bank"] = qgis_shapefile["Name_Bank"].str.replace('ئ','ی')
qgis_shapefile["Name_Bank"] = qgis_shapefile["Name_Bank"].str.strip()

def change_peyman(x):
    
    peyman = {
        '1020201' : '1020202',
        '1020202' : '1020201',
        '1050101' : '1050102',
        '1050102' : '1050101',
        '1070203' : '1070204',
        '1070204' : '1070203',
        '1080201' : '1080202',
        '1080202' : '1080201',
        '1090103' : '1090104',
        '1090104' : '1090103',
        '1090302' : '1090303',
        '1090303' : '1090302',
        '1000000' : ''
    }
    
    if x in list(peyman.keys()):
        return peyman[x]
    else:
        return x

qgis_shapefile["Code_Bank"] = qgis_shapefile["Code_Bank"].apply(lambda x : change_peyman(x))

qgis_shapefile["شناسه"] = qgis_shapefile["Code_Bank"] + "-" + qgis_shapefile["Name_Bank"]

tmp = pd.DataFrame()
for idf, df in qgis_shapefile.groupby(["شناسه"]):
    if "-" in list(df.loc[:, "شناسه"]):
        df["Area_Percent"] = 1
    else:
        a = df['Area_GIS'].sum()
        df["Area_Percent"] = df["Area_GIS"] / a
    
    tmp = pd.concat([tmp, df])

qgis_shapefile = tmp
   


QGIS = pd.merge(
    qgis_shapefile,
    Output_Method_01,
    how='outer',
    on='شناسه'
)

QGIS["Area_Converted"] = QGIS["مساحت"] * QGIS["Area_Percent"]
QGIS["IR_Year_Converted"] = QGIS["نیاز آبی سالانه"] * QGIS["Area_Percent"]
QGIS["IR_Tir_Converted"] = QGIS["نیاز آبی تیر ماه"] * QGIS["Area_Percent"]

QGIS["Hydromodel_Tir_m3_ha"] = QGIS["IR_Tir_Converted"] / (QGIS["Area_Converted"] / 10000)
QGIS["Hydromodel_Tir_lit_s_ha"] = (QGIS["IR_Tir_Converted"] * 1000 / 31 / 24 / 3600) / (QGIS["Area_Converted"] / 10000)

QGIS = QGIS[[
    'geometry',
    'fid',
    'Code_Bank',
    'Name_Bank',
    'Tozihat',
    'Area_GIS',
    'شناسه',
    'Area_Percent',
    'مساحت',
    'نیاز آبی سالانه',
    'نیاز آبی تیر ماه',
    'نام نوع لکه',
    'Area_Converted',
    'IR_Year_Converted',
    'IR_Tir_Converted',
    'Hydromodel_Tir_m3_ha',
    'Hydromodel_Tir_lit_s_ha'
]]

QGIS.columns = ['geometry',
                'fid',
                'Code_Bank',
                'Name_Bank',
                'Tozihat',
                'Area_GIS',
                'ID',
                'Area_Shapefile_Percent',
                'Area_Bank',
                'IR_Year_Bank',
                'IR_Tir_Bank',
                'Type_Spot',
                'Area_Bank_Converted',
                'IR_Year_Bank_Converted',
                'IR_Tir_Bank_Converted',
                'Hydromodel_Tir_m3_ha',
                'Hydromodel_Tir_lit_s_ha']


QGIS["IWR_Tir_m3"] = QGIS["Hydromodel_Tir_m3_ha"] * QGIS["Area_Bank_Converted"] / 10000

QGIS = QGIS[[
    'geometry',
    'fid',
    'Code_Bank',
    'Name_Bank',
    'Tozihat',
    'Type_Spot',
    'Area_Bank_Converted',
    'IWR_Tir_m3'
 ]]

QGIS.columns = [
    'geometry',
    'fid',
    'Code_Bank',
    'Name_Bank',
    'Tozihat',
    'Spot',
    'Area_LET',
    'IWR_Tir'
]
  

# date = datetime.today().strftime('%Y%m%d_%H%M')
# file_name = PROJECT_PATH + "assets/report/QGIS_Existed_" + date + ".xlsx"
# with pd.ExcelWriter(path=file_name, engine="openpyxl", mode="w") as writer:
#     QGIS.to_excel(writer, index=False, sheet_name="Sheet1")

file_name = PROJECT_PATH + "assets/report/GIS_Layer/Mashhad_Landscape_Existed_" + date + ".shp"
QGIS.to_file(file_name, encoding='utf-8')

DataLayerError: Failed to create file C:\thesis\Shirazi_Code\Landscape_Evapotranspirationassets/report/GIS_Layer\Mashhad_Landscape_Existed_20260813.shp: No such file or directory

# Calculate Hydromodole for Existed Layer

In [34]:
IDs_Asle = ["08", "09"]

df = result_method_01.query('`زیرمجموعه هر قلم` != @IDs_Asle').reset_index(drop=True)

df = df[[
    "منطقه",
    "ناحیه",
    "پیمان",
    "آدرس",
    "نام نوع لکه",
    "مقدار آیتم",
    "IR",
    "IR_M04"
]] 
    
df.columns = [
    "منطقه",
    "ناحیه",
    "پیمان",
    "آدرس",
    "نوع لکه",
    "مساحت",
    "نیاز آبی سالانه",
    "نیاز آبی تیر ماه"
]

Area = df.pivot_table(
    values=[
        "مساحت"
    ],
    index=[
        "منطقه",
        "ناحیه",
        "پیمان",
        "آدرس",
        "نوع لکه"
    ],
    aggfunc={
        "مساحت": "sum"
    }
).fillna(0).reset_index(drop=False)

IR = df.pivot_table(
    values=[
        "نیاز آبی سالانه",
        "نیاز آبی تیر ماه"
    ],
    index=[
        "منطقه",
        "ناحیه",
        "پیمان",
        "آدرس",
        "نوع لکه"
    ],
    aggfunc={
        "نیاز آبی سالانه": "sum",
        "نیاز آبی تیر ماه" : "sum"
    }
).fillna(0).reset_index(drop=False)

Output_Exsited = pd.merge(
    left=Area,
    right=IR,
    how='outer', 
    on=[
        "منطقه",
        "ناحیه",
        "پیمان",
        "آدرس",
        "نوع لکه"
    ]
)

Output_Exsited_Layer = Output_Exsited


# Extract Hydromodol for Region - District

Output_Exsited = Output_Exsited.groupby(['منطقه', 'ناحیه', 'نوع لکه']).agg({
    'مساحت': 'sum',
    'نیاز آبی سالانه': 'sum',
    'نیاز آبی تیر ماه': 'sum'
}).rename(columns={
    'مساحت' : 'Area_m2',
    'نیاز آبی سالانه' : 'IWR_Year_m3',
    'نیاز آبی تیر ماه' : 'IWR_Tir_m3'
})

Output_Exsited = Output_Exsited.assign(
    Hy_Tir_m3h = (Output_Exsited['IWR_Tir_m3'] / (Output_Exsited['Area_m2'] / 10000)),
    Hy_Tir_lsh = (Output_Exsited['IWR_Tir_m3'] * 1000 / 31 / 24 / 3600) / (Output_Exsited['Area_m2'] / 10000)
).reset_index()



date = datetime.today().strftime('%Y%m%d')
file_name = PROJECT_PATH + "assets/report/Hydromodol_Existed_Layer_" + date + ".xlsx"
with pd.ExcelWriter(path=file_name, engine="openpyxl", mode="w") as writer:
    Output_Exsited.pivot(index=['منطقه', 'ناحیه'], columns='نوع لکه', values='Hy_Tir_lsh').reset_index().to_excel(writer, index=False, sheet_name="Sheet1")

# Calculate Hydromodole for Tafsili And Developing Layer

In [35]:
pd.options.display.max_rows = 20

Parks = [
    'پارک های زیر 6 هکتار',
    'پارک های بالای 10 هکتار',
    'پارک های بین 6 تا 10 هکتار'
]


a = Output_Exsited_Layer.groupby(['منطقه','نوع لکه']).agg({
    'مساحت': 'sum',
    'نیاز آبی سالانه': 'sum',
    'نیاز آبی تیر ماه': 'sum'
}).reset_index().query('`نوع لکه` == @Parks')


b = a.groupby(['منطقه']).agg({
    'مساحت' : 'sum'
}).reset_index().rename(columns={'مساحت': 'مساحت کل'})


c = pd.merge(
    a,
    b,
    how='outer',
    on='منطقه'
).rename(columns={
    'منطقه' : 'Region',
    'نوع لکه' : 'Spot',
    'مساحت' : 'Area_m2',
    'نیاز آبی سالانه' : 'IWR_Year_m3',
    'نیاز آبی تیر ماه' : 'IWR_Tir_m3',
    'مساحت کل' : 'Total_Area_m2'
})

c = c.assign(
    Hy_Tir_m3h = (c['IWR_Tir_m3'] / (c['Area_m2'] / 10000)),
    Hy_Tir_lsh = (c['IWR_Tir_m3'] * 1000 / 31 / 24 / 3600) / (c['Area_m2'] / 10000)
)


c['x'] = c['Area_m2'] * c['Hy_Tir_m3h'] / c['Total_Area_m2']
c['y'] = c['Area_m2'] * c['Hy_Tir_lsh'] / c['Total_Area_m2']


c = c.groupby(['Region']).agg({
    'x' : 'sum',
    'y' : 'sum'
}).reset_index().rename(columns={
    'x' : 'Hy_Tir_m3h',
    'y' : 'Hy_Tir_lsh'
})


date = datetime.today().strftime('%Y%m%d')
file_name = PROJECT_PATH + "assets/report/Hydromodol_Tafsili_Developing_Layer_" + date + ".xlsx"
with pd.ExcelWriter(path=file_name, engine="openpyxl", mode="w") as writer:
    c.to_excel(writer, index=False, sheet_name="Sheet1")

In [36]:
c

   Region  Hy_Tir_m3h  Hy_Tir_lsh
0      01    2,692.07        1.01
1      02    2,641.14        0.99
2      03    2,301.62        0.86
3      04    2,308.01        0.86
4      05    2,424.41        0.91
5      06    2,504.74        0.94
6      07    1,863.99        0.70
7      08    2,034.98        0.76
8      09    2,127.07        0.79
9      10    2,514.81        0.94
10     11    2,323.87        0.87
11     12    2,497.47        0.93
12     13    2,566.52        0.96

# Export for QGIS - Tafsili Layer

In [ ]:

c.loc[8, "Hy_Tir_lsh"] = c.loc[8, "Hy_Tir_lsh"] * .75

tafsili_shapefile = gpd.read_file("../assets/input/GIS_Layer/Mashhad_Landscape_Tafsili.shp")

df = tafsili_shapefile.groupby(['Region']).agg({
    'Area_GIS' : 'sum'
}).reset_index()

tafsili_shapefile = pd.merge(
    tafsili_shapefile,
    c,
    how='outer',
    on='Region'
)

tafsili_shapefile = tafsili_shapefile\
    .assign(Area_LET = lambda x : x.Area_GIS * 0.7)\
    .assign(IWR_Tir = lambda x : x.Hy_Tir_m3h * x.Area_LET / 10000)\
    .drop(columns=["Hy_Tir_m3h", "Hy_Tir_lsh"])

file_name = PROJECT_PATH + "assets/report/GIS_Layer/Mashhad_Landscape_Tafsili_" + date + ".shp"
tafsili_shapefile.to_file(file_name, encoding='utf-8')

# Export for QGIS - Developing Layer

In [ ]:
developing_shapefile = gpd.read_file("../assets/input/GIS_Layer/Mashhad_Landscape_Developing_20210125.shp")

df = developing_shapefile.groupby(['Region']).agg({
    'Area_GIS' : 'sum'
}).reset_index()

developing_shapefile = pd.merge(
    developing_shapefile,
    c,
    how='outer',
    on='Region'
)

developing_shapefile = developing_shapefile\
    .assign(Area_LET = lambda x : x.Area_GIS * 0.7)\
    .assign(IWR_Tir = lambda x : x.Hy_Tir_m3h * x.Area_LET / 10000)\
    .drop(columns=["Hy_Tir_m3h", "Hy_Tir_lsh"])

file_name = PROJECT_PATH + "assets/report/GIS_Layer/Mashhad_Landscape_Developing_" + date + ".shp"
developing_shapefile.to_file(file_name, encoding='utf-8')

# Export for QGIS - UnDeveloping Layer

In [ ]:
undeveloping_shapefile = gpd.read_file("../assets/input/GIS_Layer/Mashhad_Landscape_UnDeveloping.shp")

df = undeveloping_shapefile.groupby(['Region']).agg({
    'Area_GIS' : 'sum'
}).reset_index()

undeveloping_shapefile = pd.merge(
    undeveloping_shapefile,
    c,
    how='outer',
    on='Region'
)

undeveloping_shapefile = undeveloping_shapefile\
    .assign(Area_LET = lambda x : x.Area_GIS * 0.04 * 0.7)\
    .assign(IWR_Tir = lambda x : x.Hy_Tir_m3h * x.Area_LET / 10000)\
    .drop(columns=["Hy_Tir_m3h", "Hy_Tir_lsh"])

file_name = PROJECT_PATH + "assets/report/GIS_Layer/Mashhad_Landscape_UnDeveloping_" + date + ".shp"
undeveloping_shapefile.to_file(file_name, encoding='utf-8')

# Error Check Shapefile

# Check Error
import json
import fiona
from shapely.geometry import shape 

#Read data
collection = list(fiona.open("assets/data/GIS_Layer/Mashhad_Landscape_Developing_20210125.shp",'r'))
df1 = pd.DataFrame(collection)

#Check Geometry
def isvalid(geom):
    try:
        shape(geom)
        return 1
    except:
        return 0
df1['isvalid'] = df1['geometry'].apply(lambda x: isvalid(x))
df1 = df1[df1['isvalid'] == 1]
collection = json.loads(df1.to_json(orient='records'))

#Convert to geodataframe
gdf = gpd.GeoDataFrame.from_features(collection)

<div style="direction:rtl;line-height:300%;" id="section3">
    <font face="B Titr" size=4>
        <center><h3>روش دوم (دکتر سلطانی)</h3></center>    
    </font>
</div>

Month_Name = ["M01", "M02", "M03", "M04", "M05", "M06", "M07", "M08", "M09", "M10", "M11", "M12"]

result_method_02 = dataset_coeff.copy()
















for i, value in enumerate(Month_Name):    
    result_method_02["KL_" + value] = result_method_02["Ks_" + value] * result_method_02["درصد مساحت گونه در لکه"] * result_method_02["Kd_v2"] * result_method_02["Kmc_" + value]

for i, value in enumerate(Month_Name):    
    result_method_02["LET_" + value] = result_method_02["PET_" + value] * result_method_02["KL_" + value]

for i, value in enumerate(Month_Name):
    result_method_02["IR_" + value] = ((result_method_02["LET_" + value] - result_method_02["Effe_Precip_" + value]) * result_method_02["n_Day_" + value] / result_method_02["IE_" + value]) * result_method_02["مقدار آیتم"] / 1000
    result_method_02.loc[result_method_02["IR_" + value] < 0, ["IR_" + value]] = 0

result_method_02["IR"] = result_method_02[["IR_M01", "IR_M02", "IR_M03", "IR_M04", "IR_M05", "IR_M06", "IR_M07", "IR_M08", "IR_M09", "IR_M10", "IR_M11", "IR_M12"]].sum(axis=1)

file_name = PROJECT_PATH + "assets/report/" + "Method_02.xlsx"
with pd.ExcelWriter(path=file_name, engine="openpyxl", mode="w") as writer:
    result_method_02.to_excel(writer, index=True, sheet_name="نتایج کلی")

pd.options.display.max_rows = 6
pd.options.display.float_format = "{:,.2f}".format
result_method_02

<div style="direction:rtl;line-height:300%;" id="section3">
    <font face="B Titr" size=5>
        <right><h۴>توضیحات:</h۴></right>    
    </font>    
    <font face="B Zar" size=5>
        <right align="justify">
            مساحت فضای سبز گونه های مختلف
        </right>
    </font>    
</div>

IDs_Asle = ["08", "09"]

df = result_method_02[["منطقه", "ناحیه", "پیمان", "آدرس", "نوع لکه", "نوع قلم", "زیرمجموعه هر قلم", "مقدار آیتم", "IR", "IR_M04", "نام نوع قلم", "نام زیرمجموعه هر قلم"]]

df = df.query('`زیرمجموعه هر قلم` != @IDs_Asle').reset_index()

result = df.pivot_table(
    values=["مقدار آیتم", "IR", "IR_M04"],
    index=["منطقه"],
#     columns=["نام نوع قلم", "نام زیرمجموعه هر قلم"],
    aggfunc={"مقدار آیتم": "sum",
            "IR": "sum",
            "IR_M04" : "sum"},
#     margins=True,
#     margins_name="جمع کل",
).fillna(0).reset_index(drop=False)


result['IR'] = result['IR'] / 1000
result['IR_M04'] = result['IR_M04'] / 1000
result['مقدار آیتم'] = result['مقدار آیتم'] / 10000

result = result.rename(columns={'IR' : 'نیاز آب آبیاری سالانه',
                                'IR_M04' : 'نیاز آب آبیاری تیر ماه',
                                'مقدار آیتم' : 'مساحت'})

file_name = PROJECT_PATH + "assets/report/Method_02.xlsx"
with pd.ExcelWriter(path=file_name, engine="openpyxl", mode="a") as writer:
    result.to_excel(writer, index=False, sheet_name="مساحت - نیاز آبی - منطقه")
    
display(result)

<div style="direction:rtl;line-height:300%;" id="section3">
    <font face="B Titr" size=5>
        <right><h۴>توضیحات:</h۴></right>    
    </font>    
    <font face="B Zar" size=5>
        <right align="justify">
            نیاز آبی گونه های مختلف
        </right>
    </font>    
</div>

pd.options.display.max_rows = 20
pd.options.display.float_format = "{:,.2f}".format

IDs_Asle = ["08", "09"]

df = result_method_02[["منطقه", "ناحیه", "پیمان", "آدرس", "نوع لکه", "نوع قلم", "زیرمجموعه هر قلم", "مقدار آیتم", "IR", "IR_M04", "نام نوع قلم", "نام زیرمجموعه هر قلم"]]

df = df.query('`زیرمجموعه هر قلم` != @IDs_Asle').reset_index()

result = df.pivot_table(
    values=["IR", "IR_M04"],
    index=["منطقه"],
    columns=["نام نوع قلم"],
    aggfunc={"IR": "sum",
            "IR_M04" : "sum"},
    margins=True,
    margins_name="جمع کل",
).fillna(0).reset_index(drop=False)

file_name = PROJECT_PATH + "assets/report/" + "Method_02.xlsx"
with pd.ExcelWriter(path=file_name, engine="openpyxl", mode="a") as writer:
    result.to_excel(writer, index=True, sheet_name="نیازآبی - منطقه")
    
display(result)