In [ ]:
import os

# بررسی اینکه آیا اصلاً پایتون این پوشه را پیدا می‌کند؟
if os.path.exists(REPORT_DIR):
    print("پوشه پیدا شد. لیست فایل‌های موجود در آن:")
    # چاپ کردن اسم دقیق تمام فایل‌های داخل این پوشه
    print(os.listdir(REPORT_DIR))
else:
    print("خطا: پایتون اصلاً نتوانست پوشه report را پیدا کند! مسیر را چک کنید.")

پوشه پیدا شد. لیست فایل‌های موجود در آن:
['data_cleansing_20210216.xlsx', 'data_cleansing_20210218.xlsx', 'data_cleansing_20210313.xlsx', 'data_cleansing_20210319.xlsx', 'data_cleansing_20210417.xlsx', 'data_errors_20210216.xlsx', 'data_errors_20210218.xlsx', 'data_errors_20210313.xlsx', 'data_errors_20210319.xlsx', 'data_errors_20210417.xlsx', 'Old', 'Tree_Calculation.xlsx']

In [17]:
import pandas as pd


PROJECT_PATH = r"C:\thesis\Shirazi_Code\Landscape_Evapotranspiration\assets\output\data_cleansing_20210417.xlsx"

data = pd.read_excel(
    PROJECT_PATH,
    engine = "openpyxl",
    dtype={
        "شناسه": str,
        "منطقه": str,
        "ناحیه": str,
        "پیمان": str,
        "آدرس": str,
        "نوع لکه": str,
        "نوع قلم": str,
        "زیرمجموعه هر قلم": str
    }
)

In [18]:
import pandas as pd


PROJECT_PATH = r"C:\thesis\Shirazi_Code\Landscape_Evapotranspiration\assets\output\data_cleansing_20210216.xlsx"

data2 = pd.read_excel(
    PROJECT_PATH,
    engine = "openpyxl",
    dtype={
        "شناسه": str,
        "منطقه": str,
        "ناحیه": str,
        "پیمان": str,
        "آدرس": str,
        "نوع لکه": str,
        "نوع قلم": str,
        "زیرمجموعه هر قلم": str
    }
)

In [15]:
df["نام نوع قلم"].unique()

array(['درخت و درختچه'], dtype=object)

In [13]:
df = data.query('`نوع قلم` == "07"')

In [14]:
df

,شناسه,منطقه,ناحیه,پیمان,آدرس,نوع لکه,نوع قلم,زیرمجموعه هر قلم,مقدار آیتم,مساحت آدرس,مساحت پیمان,نوع آیتم,نام پیمان,نام لکه,نام نوع لکه,نام نوع قلم,نام زیرمجموعه هر قلم,مقدار آیتم خام
4,01.01.01.001.04-07.08,01,01,01,001,04,07,08,365.0,2718.0,122306.0,ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار ابوذر و لچکی ها,آیلند ها,درخت و درختچه,اصله,365.0
21,01.01.01.002.04-07.07,01,01,01,002,04,07,07,243.0,16254.0,122306.0,ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار احمد آباد,آیلند ها,درخت و درختچه,متر مربع,243.0
22,01.01.01.002.04-07.08,01,01,01,002,04,07,08,692.0,16254.0,122306.0,ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار احمد آباد,آیلند ها,درخت و درختچه,اصله,692.0
23,01.01.01.002.04-07.04,01,01,01,002,04,07,04,243.0,16254.0,122306.0,ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار احمد آباد,آیلند ها,درخت و درختچه,آبیاری تحت فشار,243.0
40,01.01.01.003.04-07.08,01,01,01,003,04,07,08,238.0,3184.0,122306.0,ریزآیتمی,الف ناحیه 1 منطقه 1,آیلند بلوار بعثت,آیلند ها,درخت و درختچه,اصله,238.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27329,13.02.01.036.08-07.08,13,02,01,036,08,07,08,16.0,293.0,66059.7,ریزآیتمی,ناحیه 2 منطقه ثامن,پارک اتابک,پارک های زیر 6 هکتار,درخت و درختچه,اصله,16.0
27345,13.02.01.037.08-07.03,13,02,01,037,08,07,03,219.0,6626.0,66059.7,ریزآیتمی,ناحیه 2 منطقه ثامن,پارک ره باغ بهشت,پارک های زیر 6 هکتار,درخت و درختچه,آبیاری شلنگی,219.0
27346,13.02.01.037.08-07.08,13,02,01,037,08,07,08,219.0,6626.0,66059.7,ریزآیتمی,ناحیه 2 منطقه ثامن,پارک ره باغ بهشت,پارک های زیر 6 هکتار,درخت و درختچه,اصله,219.0
27364,13.02.01.038.08-07.08,13,02,01,038,08,07,08,52.0,1174.7,66059.7,ریزآیتمی,ناحیه 2 منطقه ثامن,پارک سارا,پارک های زیر 6 هکتار,درخت و درختچه,اصله,52.0
27378,13.02.01.039.08-07.08,13,02,01,039,08,07,08,49.0,2233.0,66059.7,ریزآیتمی,ناحیه 2 منطقه ثامن,پارک پردیس,پارک های زیر 6 هکتار,درخت و درختچه,اصله,49.0

In [ ]:
result = pd.DataFrame(columns=data.columns)

for idf, df in data.groupby(["منطقه", "ناحیه", "پیمان", "آدرس"]):
    df = df.reset_index(drop=True)
    display(df)
    TI_Check = df.query('`نوع قلم` == "07" and `زیرمجموعه هر قلم` == ["01", "02", "03", "04"]').shape[0]
    TI_Index = df.query('`نوع قلم` == "07" and `زیرمجموعه هر قلم` == ["01", "02", "03", "04"]').index.to_list()

    if TI_Check > 0:

        tree_area = 9

        if df[df["زیرمجموعه هر قلم"] == '08'].shape[0] > 0:
            if df.query('`نوع قلم` == "07" and `زیرمجموعه هر قلم` == ["01"]').shape[0] > 0:
                Asle_Tree = df[df['زیرمجموعه هر قلم'] == '08'].iloc[0]["مقدار آیتم"]
                Independent_Tree_noGravity = df.query('`نوع قلم` == "07" and `زیرمجموعه هر قلم` == ["02", "03", "04"]')["مقدار آیتم"].sum()
                df.loc[(df['نوع قلم'] == "07") & (df['زیرمجموعه هر قلم'] == "01"), 'مقدار آیتم'] = Asle_Tree - Independent_Tree_noGravity
                Independent_Tree = df.query('`نوع قلم` == "07" and `زیرمجموعه هر قلم` == ["01", "02", "03", "04"]')["مقدار آیتم"].sum()
            else:
                Asle_Tree = df[df['زیرمجموعه هر قلم'] == '08'].iloc[0]["مقدار آیتم"]
                Independent_Tree = df.query('`نوع قلم` == "07" and `زیرمجموعه هر قلم` == ["01", "02", "03", "04"]')["مقدار آیتم"].sum()
        else:
            Asle_Tree = df.query('`نوع قلم` == "07" and `زیرمجموعه هر قلم` == ["01", "02", "03", "04"]')["مقدار آیتم"].sum()
            Independent_Tree = df.query('`نوع قلم` == "07" and `زیرمجموعه هر قلم` == ["01", "02", "03", "04"]')["مقدار آیتم"].sum()

        Address_Area = df[df["نوع آیتم"] == "ریزآیتمی"].iloc[0]["مساحت آدرس"]

        Spot_Class = df.iloc[0]["نوع لکه"]

        if Spot_Class in ['07', '08', '09', '10', '11', '12', '13']:
            Tree_Area = Address_Area / Asle_Tree
            tree_area = 9 if Tree_Area > 9 else Tree_Area
        elif Spot_Class in ['01', '02']:
            Tree_Area = Address_Area * 1.1 / Asle_Tree
            tree_area = 9 if Tree_Area > 9 else Tree_Area
        elif Spot_Class in ['03', '04', '05', '06']:
            Tree_Area = Address_Area * 1.3 / Asle_Tree
            tree_area = 9 if Tree_Area > 9 else Tree_Area                

        for i in TI_Index:
            df.loc[i, "مقدار آیتم"] = df.loc[i, "مقدار آیتم"] * tree_area

        tmp = df.iloc[[0], :]
        tmp.loc[0, "نوع قلم"] = "07"
        tmp.loc[0, "زیرمجموعه هر قلم"] = "09"
        tmp.loc[0, "شناسه"] = (tmp.loc[0, "منطقه"] + "." + tmp.loc[0, "ناحیه"] + "." + tmp.loc[0, "پیمان"] + "."
                               + tmp.loc[0, "آدرس"] + "." + tmp.loc[0, "نوع لکه"] + "-" + tmp.loc[
                                   0, "نوع قلم"] + "." + tmp.loc[0, "زیرمجموعه هر قلم"])
        tmp.loc[0, "مقدار آیتم"] = Independent_Tree
        tmp.loc[0, "مقدار آیتم خام"] = Independent_Tree
        tmp.loc[0, "نام نوع قلم"] = "درخت و درختچه"
        tmp.loc[0, "نام زیرمجموعه هر قلم"] = "اصله مستقل"
        tmp.loc[0, "نوع آیتم"] = "ریزآیتمی"
        tmp.loc[0, "مساحت آدرس"] = df[df["نوع آیتم"] == "ریزآیتمی"].iloc[0]["مساحت آدرس"]
        tmp.loc[0, "مساحت پیمان"] = df[df["نوع آیتم"] == "ریزآیتمی"].iloc[0]["مساحت پیمان"]

        df = pd.concat([df, tmp])
        result = pd.concat([result, df])
    else:
        result = pd.concat([result, df])

result = result.reset_index(drop=True)

                    شناسه منطقه  ... نام زیرمجموعه هر قلم مقدار آیتم خام
0   01.01.01.001.04-56.07    01  ...             متر مربع         1704.0
1   01.01.01.001.04-51.07    01  ...             متر مربع          784.0
2   01.01.01.001.04-52.07    01  ...             متر مربع          210.0
3   01.01.01.001.04-54.07    01  ...             متر مربع           20.0
4   01.01.01.001.04-07.08    01  ...                 اصله          365.0
5   01.01.01.001.04-06.07    01  ...             متر مربع         1704.0
6   01.01.01.001.04-06.03    01  ...         آبیاری شلنگی          299.0
7   01.01.01.001.04-06.02    01  ...        آبیاری تانکری         1405.0
8   01.01.01.001.04-01.03    01  ...         آبیاری شلنگی          784.0
9   01.01.01.001.04-01.07    01  ...             متر مربع          784.0
10  01.01.01.001.04-02.06    01  ...                گل رز          196.0
11  01.01.01.001.04-02.05    01  ...    سایر گل های دایمی           14.0
12  01.01.01.001.04-02.07    01  ...             متر مربع          210.0
13  01.01.01.001.04-02.03    01  ...         آبیاری شلنگی          210.0
14  01.01.01.001.04-04.07    01  ...             متر مربع           20.0
15  01.01.01.001.04-04.03    01  ...         آبیاری شلنگی           20.0

[16 rows x 18 columns]

                    شناسه منطقه  ... نام زیرمجموعه هر قلم مقدار آیتم خام
0   01.01.01.002.04-57.07    01  ...             متر مربع          243.0
1   01.01.01.002.04-56.07    01  ...             متر مربع         1970.0
2   01.01.01.002.04-51.07    01  ...             متر مربع        12343.0
3   01.01.01.002.04-52.07    01  ...             متر مربع          780.0
4   01.01.01.002.04-54.07    01  ...             متر مربع          850.0
5   01.01.01.002.04-07.07    01  ...             متر مربع          243.0
6   01.01.01.002.04-07.08    01  ...                 اصله          692.0
7   01.01.01.002.04-07.04    01  ...      آبیاری تحت فشار          243.0
8   01.01.01.002.04-06.07    01  ...             متر مربع         1970.0
9   01.01.01.002.04-06.04    01  ...      آبیاری تحت فشار         1970.0
10  01.01.01.002.04-01.07    01  ...             متر مربع        12411.0
11  01.01.01.002.04-01.04    01  ...      آبیاری تحت فشار        10843.0
12  01.01.01.002.04-01.03    01  ...         آبیاری شلنگی         1568.0
13  01.01.01.002.04-02.05    01  ...    سایر گل های دایمی          300.0
14  01.01.01.002.04-02.07    01  ...             متر مربع          780.0
15  01.01.01.002.04-02.06    01  ...                گل رز          480.0
16  01.01.01.002.04-02.04    01  ...      آبیاری تحت فشار          780.0
17  01.01.01.002.04-04.07    01  ...             متر مربع          850.0
18  01.01.01.002.04-04.04    01  ...      آبیاری تحت فشار          850.0

[19 rows x 18 columns]

C:\Users\POOYA\miniconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

                    شناسه منطقه  ... نام زیرمجموعه هر قلم مقدار آیتم خام
0   01.01.01.003.04-94.07    01  ...             متر مربع           16.0
1   01.01.01.003.04-56.07    01  ...             متر مربع          970.0
2   01.01.01.003.04-51.07    01  ...             متر مربع         2076.0
3   01.01.01.003.04-52.07    01  ...             متر مربع           77.0
4   01.01.01.003.04-54.07    01  ...             متر مربع           45.0
5   01.01.01.003.04-07.08    01  ...                 اصله          238.0
6   01.01.01.003.04-06.07    01  ...             متر مربع          970.0
7   01.01.01.003.04-06.03    01  ...         آبیاری شلنگی          970.0
8   01.01.01.003.04-01.03    01  ...         آبیاری شلنگی         2076.0
9   01.01.01.003.04-01.07    01  ...             متر مربع         2076.0
10  01.01.01.003.04-02.07    01  ...             متر مربع           77.0
11  01.01.01.003.04-02.03    01  ...         آبیاری شلنگی           77.0
12  01.01.01.003.04-02.06    01  ...                گل رز           77.0
13  01.01.01.003.04-04.03    01  ...         آبیاری شلنگی           45.0
14  01.01.01.003.04-04.07    01  ...             متر مربع           45.0

[15 rows x 18 columns]

                    شناسه منطقه  ... نام زیرمجموعه هر قلم مقدار آیتم خام
0   01.01.01.004.04-57.07    01  ...             متر مربع            1.0
1   01.01.01.004.04-56.07    01  ...             متر مربع         2457.0
2   01.01.01.004.04-51.07    01  ...             متر مربع          333.0
3   01.01.01.004.04-52.07    01  ...             متر مربع          166.0
4   01.01.01.004.04-54.07    01  ...             متر مربع           55.0
5   01.01.01.004.04-07.03    01  ...         آبیاری شلنگی            1.0
6   01.01.01.004.04-07.07    01  ...             متر مربع            1.0
7   01.01.01.004.04-07.08    01  ...                 اصله          302.0
8   01.01.01.004.04-06.07    01  ...             متر مربع         2522.0
9   01.01.01.004.04-06.03    01  ...         آبیاری شلنگی         2522.0
10  01.01.01.004.04-01.03    01  ...         آبیاری شلنگی          333.0
11  01.01.01.004.04-01.07    01  ...             متر مربع          333.0
12  01.01.01.004.04-02.07    01  ...             متر مربع          166.0
13  01.01.01.004.04-02.06    01  ...                گل رز          141.0
14  01.01.01.004.04-02.05    01  ...    سایر گل های دایمی           25.0
15  01.01.01.004.04-02.03    01  ...         آبیاری شلنگی          166.0
16  01.01.01.004.04-04.03    01  ...         آبیاری شلنگی           55.0
17  01.01.01.004.04-04.07    01  ...             متر مربع           55.0

[18 rows x 18 columns]

C:\Users\POOYA\miniconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

                    شناسه منطقه  ... نام زیرمجموعه هر قلم مقدار آیتم خام
0   01.01.01.005.04-56.07    01  ...             متر مربع          162.0
1   01.01.01.005.04-51.07    01  ...             متر مربع         3570.0
2   01.01.01.005.04-52.07    01  ...             متر مربع          326.0
3   01.01.01.005.04-54.07    01  ...             متر مربع          100.0
4   01.01.01.005.04-07.08    01  ...                 اصله          273.0
5   01.01.01.005.04-91.07    01  ...             متر مربع          214.0
6   01.01.01.005.04-06.03    01  ...         آبیاری شلنگی          162.0
7   01.01.01.005.04-06.07    01  ...             متر مربع          162.0
8   01.01.01.005.04-01.07    01  ...             متر مربع         3810.0
9   01.01.01.005.04-01.03    01  ...         آبیاری شلنگی         3810.0
10  01.01.01.005.04-02.03    01  ...         آبیاری شلنگی          391.0
11  01.01.01.005.04-02.06    01  ...                گل رز          386.0
12  01.01.01.005.04-02.07    01  ...             متر مربع          391.0
13  01.01.01.005.04-02.05    01  ...    سایر گل های دایمی            5.0
14  01.01.01.005.04-04.07    01  ...             متر مربع          100.0
15  01.01.01.005.04-04.03    01  ...         آبیاری شلنگی          100.0

[16 rows x 18 columns]

                    شناسه منطقه  ... نام زیرمجموعه هر قلم مقدار آیتم خام
0   01.01.01.006.04-56.07    01  ...             متر مربع         2142.0
1   01.01.01.006.04-51.07    01  ...             متر مربع         3446.0
2   01.01.01.006.04-52.07    01  ...             متر مربع           27.0
3   01.01.01.006.04-07.08    01  ...                 اصله          286.0
4   01.01.01.006.04-06.07    01  ...             متر مربع         2142.0
5   01.01.01.006.04-06.04    01  ...      آبیاری تحت فشار         2142.0
6   01.01.01.006.04-01.07    01  ...             متر مربع         3446.0
7   01.01.01.006.04-01.04    01  ...      آبیاری تحت فشار         3446.0
8   01.01.01.006.04-02.06    01  ...                گل رز           27.0
9   01.01.01.006.04-02.07    01  ...             متر مربع           27.0
10  01.01.01.006.04-02.03    01  ...         آبیاری شلنگی           27.0

[11 rows x 18 columns]